server:
  port: 8083


spring:
  security:
    user:
      name: zytech
      password: zytech2018

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8081/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8082/eureka/

