server:
  port: 9999

spring:
  application:
    name: springcloud-product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://zytech:zytech2018@localhost:8081/eureka
    #eureka.client.healthcheck.enabled=true should only be set in application.yml. Setting the value in bootstrap.yml
    healthcheck:
      enabled: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true