spring:
  application:
    name: config-repo
  cloud:
    config:
      server:
        git:
          uri: git@github.com:KINGLBT/config-repo.git
          skip-ssl-validation: true
          timeout: 20
          clone-on-start: true
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAy7wa00UzNS5XdQYQ/EAEjLGy3vAokZfOSXvlRs6ZkqG6j21k
            r1qElp9Twv2YmxPMv1kGBn2CRHScWMWAMo7fHomWuh2duLsLBEXTO8GUyLpEbQ4L
            i6eS1zCkzABeyc0HFmrrhMpfNbknnGXhztbhwIfhraaIaUR5AIeKkVKrg4GlrEPa
            a3Fk5FGNPgHS4CCdJCASmGbJfsS7q6eG3KYlMO91BzyQmHxY2uehF/+Qq4BVcI+r
            vgxZEpTZrypBLgcF6I1l9ttZS4npJu6uBvL4QhrxCzO7KYei/S1esMnDihFDTLez
            a1SFG9AWTSCcryJYzUi6thlGxapKiaD/pLtqBwIDAQABAoIBACVEX1POELPlqjHJ
            zkmWHD7wMlv9ai5XqnBerW3qVMUxuEKMLCK3WBGFS3kbklKrqIRH8IY3ZyDGg+Lp
            Ha4h3EZlvKCG0lb8P+OkMiN4IZMmH2Yjb5E4MfATAdIfLzeSvX0oSbScoBXfrJM7
            P7bqL5lcQbfWApXe5JNoN7yldqIzPN/ubxNuf5b6e8HtMLqPKd0CDWOTCperBrCW
            o08miFtFdNSnvgUYtjri2tOHdlNuW4Xb0nwqWc6NkUAB6rHaqMHYz55JgpnVrxor
            xhmnCj6F36yo42j1sotUX8Yc8p4vYL/GDCu/pr2nUEiBKrlSyduAEVf7dwz+5bKs
            jR4IAsECgYEA/vyn6JmhzrPMU5Ycxpi/y5ncfiZgHH68/NohfVk7JQDKTSEy1QGH
            B87FmkL05ds3FAf924JIK5huCg+E4G3XPVI91MeFK0Yd3dYGi6fzVOvpT6NIy8qb
            13KZ3ymvOINFl3jr/Pg8hHpHf/AvptqXx5/262wGHInT0djoNunSx0kCgYEAzItS
            Kfw6+pxGTHBwDZDBVSqupM+ixmWk3ZPSqPO0TPDlhEbOI4bBe1aYS4sbByzHspVt
            rIdYFK+493sE52AlpftT5GbrjuZosV+JkeXD2NxiW5CQpVvShY+5cXdJKoWZjZtx
            8FM8gi7xcLJ/973ffacV6cSiLTaryjtO9GjMFs8CgYEA8Pvz7L6Vz/bZWv36AC+I
            xHGLk6XNG+Ej14yILiFQ5m3SxAZmNi2VYmmnE13Iehwt9759yyFb9+e9x8BXAoyM
            6aV6TkiqsPU5cNi/oul97XpwLBXTzNaVZo8moWSR90UJVliwH4q0FzhBrsZfIsBg
            xgeGo4SaWgpgqGjpPkzKKhECgYANMh/GdfasByI6egQt/oBCJPjxhF2QzBzqwm4
            JKDJJfFoqzi5SgRJdLi2hu7jc5wehU1iCAlCrGN+c81JMAa9wo0S+yDPQ0YVy1gQ
            tYYBA5bE2Xq7cEUQoMkR7OQnfh79571eB8CrlWO2JY3j6bf1X0YmoqzjxdcnYNQj
            KG+iOQKBgQCb0dCqeJiXB1FBwxFDwxWvWkh7eTN30UXvXZURmkhV8HTPk6Y76hMX
            KoUKA8VHSJrABqFTto19i+QJMmUhy7XEsVMcf/XDG+9jE/DhH0DqEFbKBJyi/r72
            Cyyf8mJ3Z2WttYCXx+6b6ctKYxHuxHP80UCYH/XAm461fdsah+oIqNBQ==
            -----END RSA PRIVATE KEY-----
          search-paths: '{application}'
          force-pull: true
          delete-untracked-branches: true
          refresh-rate: 0 # 没请求一次就刷新
  security:
    user:
      name: fykc
      password: fykc123
server:
  port: 8899