spring:
  application:
    name: springcloud-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KINGLBT/{application}
          skip-ssl-validation: true
          timeout: 10
          username: lmluomeng1992@163.com
          password: luomeng0323
          force-pull: true
          delete-untracked-branches: true
          refresh-rate: 0
        health:
          enabled: false
  security:
    user:
      name: fykc
      password: 12321
eureka:
  client:
    serviceUrl:
      defaultZone: http://zytech:zytech2018@localhost:8081/eureka
    #eureka.client.healthcheck.enabled=true should only be set in application.yml. Setting the value in bootstrap.yml
    healthcheck:
      enabled: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
server:
  port: 9977
