spring:
  application:
    name: springcloud-config-server-http
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KINGLBT/{application}
          skip-ssl-validation: true
          timeout: 10
          username: user
          password: password
          force-pull: true
          delete-untracked-branches: true
          refresh-rate: 0
  security:
    user:
      name: fykc
      password: 12321
server:
  port: 8089

